DATA SCIENCE => NUMPY

In [3]:
# INSTALL NUMPY

%pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [4]:
# import numpy

import numpy as np

In [5]:
# 1d -- 1 dimensional array

n = np.array(1)     # 0 dimensional array
print(n)

n = np.array([1,2]) # 1 square bracket  = 1 dimensional array
print(n)

n = np.array([[1,2],[2,5]])  # 2 square bracket =  2 dimensional array
print(n)

n = np.array([[[1,2],[3,4]]])   # 3 square bracket = 3 dimensional array
print(n)

1
[1 2]
[[1 2]
 [2 5]]
[[[1 2]
  [3 4]]]


DTYPE => DATATYPE IN NUMPY

In [6]:
n = np.array([2,1])
print(n)
print(n.dtype)

# type casting

n = np.array([2,1], dtype = float)
print(n)
print(n.dtype)

n = np.array([2,1], dtype = str)
print(n)
print(n.dtype)

[2 1]
int64
[2. 1.]
float64
['2' '1']
<U1


NDIM --> FIND DIEMNSION OF ARRAY

In [7]:
n = np.array([[[1,2],[3,4]]])
print(n.ndim)

3


ARANGE IN NUMPY

In [15]:
# create array in range

n = np.arange(10)   # 10 element array is created

print(n)

[0 1 2 3 4 5 6 7 8 9]


CONCATENATE FUNCTION --> COMBINE ARRAYS

In [16]:
n = np.array([1,4])
a = np.array([2,5])

b = np.concatenate((a,n))
print(b)

[2 5 1 4]


NDMIN FUNCTION --> DEFINE NO OF DIMENSIONAS FOR NUMPY

In [17]:
a = np.array([1,2], ndmin = 10)     # 1D ==> 10 D

print(a)
print(a.ndim)

[[[[[[[[[[1 2]]]]]]]]]]
10


NDITER --> ITERATE ELEMENTS IN NUMPY ARRAY

In [21]:
a = np.array([1,2,6,3,6,3,8,2])

print(a)

for i in np.nditer(a):
    print(i)

print()

for i in np.nditer(a):
    if(i%2 == 0):
        print(i)

[1 2 6 3 6 3 8 2]
1
2
6
3
6
3
8
2

2
6
6
8
2


Numpy = ALL FUCNTIONS

In [23]:
# 1. COPY FUNCTION

x = np.array([1,5])

z = x.copy()

print(x)
print(z)

[1 5]
[1 5]


In [27]:
# 2. CHANGE VALUES IN NUMPY

a = np.array([1,4])

print(a)

a[0] = 2
a[1] = 9

print(a)

n = np.array([[1,5],[3,6]])
print(n)

n[0,0] = 7
print(n)

[1 4]
[2 9]
[[1 5]
 [3 6]]
[[7 5]
 [3 6]]


In [30]:
# 3. SORT IN NUMPY

a = np.array([2,1])
print(a)

print(np.sort(a, axis = 0))  # column sort in 1d

b = np.array([[3,1],[4,6]])
print(b)
print(np.sort(b, axis = 1))  # row sort in 2d

[2 1]
[1 2]
[[3 1]
 [4 6]]
[[1 3]
 [4 6]]


In [32]:
# 4. SEARCH --> SEARCH ELEMENTS IN NUMPY

a = np.array([1,2])

x = np.where(a == 2)
print(x)       # index position of the value

y = np.where(a == 1)
print(y)  

(array([1]),)
(array([0]),)


PANDAS

In [ ]:
# IMPORT DATASET

