DATA SCIENCE => NUMPY

In [1]:
# INSTALL NUMPY

%pip install numpy

Defaulting to user installation because normal site-packages is not writeableNote: you may need to restart the kernel to use updated packages.



In [2]:
# import numpy

import numpy as np

In [3]:
# 1d -- 1 dimensional array

n = np.array(1)     # 0 dimensional array
print(n)

n = np.array([1,2]) # 1 square bracket  = 1 dimensional array
print(n)

n = np.array([[1,2],[2,5]])  # 2 square bracket =  2 dimensional array
print(n)

n = np.array([[[1,2],[3,4]]])   # 3 square bracket = 3 dimensional array
print(n)

1
[1 2]
[[1 2]
 [2 5]]
[[[1 2]
  [3 4]]]


DTYPE => DATATYPE IN NUMPY

In [4]:
n = np.array([2,1])
print(n)
print(n.dtype)

# type casting

n = np.array([2,1], dtype = float)
print(n)
print(n.dtype)

n = np.array([2,1], dtype = str)
print(n)
print(n.dtype)

[2 1]
int64
[2. 1.]
float64
['2' '1']
<U1


NDIM --> FIND DIEMNSION OF ARRAY

In [5]:
n = np.array([[[1,2],[3,4]]])
print(n.ndim)

3


ARANGE IN NUMPY

In [6]:
# create array in range

n = np.arange(10)   # 10 element array is created

print(n)

[0 1 2 3 4 5 6 7 8 9]


CONCATENATE FUNCTION --> COMBINE ARRAYS

In [7]:
n = np.array([1,4])
a = np.array([2,5])

b = np.concatenate((a,n))
print(b)

[2 5 1 4]


NDMIN FUNCTION --> DEFINE NO OF DIMENSIONAS FOR NUMPY

In [8]:
a = np.array([1,2], ndmin = 10)     # 1D ==> 10 D

print(a)
print(a.ndim)

[[[[[[[[[[1 2]]]]]]]]]]
10


NDITER --> ITERATE ELEMENTS IN NUMPY ARRAY

In [9]:
a = np.array([1,2,6,3,6,3,8,2])

print(a)

for i in np.nditer(a):
    print(i)

print()

for i in np.nditer(a):
    if(i%2 == 0):
        print(i)

[1 2 6 3 6 3 8 2]
1
2
6
3
6
3
8
2

2
6
6
8
2


Numpy = ALL FUCNTIONS

In [10]:
# 1. COPY FUNCTION

x = np.array([1,5])

z = x.copy()

print(x)
print(z)

[1 5]
[1 5]


In [11]:
# 2. CHANGE VALUES IN NUMPY

a = np.array([1,4])

print(a)

a[0] = 2
a[1] = 9

print(a)

n = np.array([[1,5],[3,6]])
print(n)

n[0,0] = 7
print(n)

[1 4]
[2 9]
[[1 5]
 [3 6]]
[[7 5]
 [3 6]]


In [12]:
# 3. SORT IN NUMPY

a = np.array([2,1])
print(a)

print(np.sort(a, axis = 0))  # column sort in 1d

b = np.array([[3,1],[4,6]])
print(b)
print(np.sort(b, axis = 1))  # row sort in 2d

[2 1]
[1 2]
[[3 1]
 [4 6]]
[[1 3]
 [4 6]]


In [13]:
# 4. SEARCH --> SEARCH ELEMENTS IN NUMPY

a = np.array([1,2])

x = np.where(a == 2)
print(x)       # index position of the value

y = np.where(a == 1)
print(y)  

(array([1]),)
(array([0]),)


PANDAS

In [14]:
# IMPORT DATASET
%pip install pandas


Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [15]:
import pandas as pd

In [16]:
data = pd.read_csv("data.csv")

HEAD AND TAIL FUNCTIONS IN PANDAS

In [17]:
# HEAD --> DISPLAY TOP VALUES

#data.head()    # default top 5 values
print(data.head(10))    # top 10 values
print()

# TAIL --> DISPLAY BOTTOM VALUES

print(data.tail())  # default bottom 5 values

   Duration          Date  Pulse  Maxpulse  Calories
0        60  '2020/12/01'    110       130     409.1
1        60  '2020/12/02'    117       145     479.0
2        60  '2020/12/03'    103       135     340.0
3        45  '2020/12/04'    109       175     282.4
4        45  '2020/12/05'    117       148     406.0
5        60  '2020/12/06'    102       127     300.0
6        60  '2020/12/07'    110       136     374.0
7       450  '2020/12/08'    104       134     253.3
8        30  '2020/12/09'    109       133     195.1
9        60  '2020/12/10'     98       124     269.0

    Duration          Date  Pulse  Maxpulse  Calories
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0


INFO IN PANDAS

In [18]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Duration  18 non-null     int64  
 1   Date      18 non-null     object 
 2   Pulse     18 non-null     int64  
 3   Maxpulse  18 non-null     int64  
 4   Calories  18 non-null     float64
dtypes: float64(1), int64(3), object(1)
memory usage: 852.0+ bytes


DROP NA FUNCTION -> DROP ALL NULL VALUES IN DATASET

DELETE WHOLE ROW OF THE NULL VALUES

In [19]:
data = data.dropna()

print(data)

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'  

FILL NA FUNCTION --> FILL ALL NULL VALUES IN DATASET

In [20]:
data = data.fillna(10)  # 10 is our own value to be filled in null values
print(data)

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'  

DROP DUPLICATE FUNCTIONS

REMOVE DUPLICATE VALUES IN DATASET

In [21]:
data = data.drop_duplicates()
print(data)

data = data.drop_duplicates(subset = "Pulse")       # drop row which have same pulse values
print(data)

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
    Duration          Date  

REPLACE VALUES IN PANDAS DATASET

In [22]:
data

Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
5         60  '2020/12/06'    102       127     300.0
7        450  '2020/12/08'    104       134     253.3
9         60  '2020/12/10'     98       124     269.0
11        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3

In [23]:
data["Duration"] = data["Duration"].replace({60: 100})

In [24]:
data

Duration          Date  Pulse  Maxpulse  Calories
0        100  '2020/12/01'    110       130     409.1
1        100  '2020/12/02'    117       145     479.0
2        100  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
5        100  '2020/12/06'    102       127     300.0
7        450  '2020/12/08'    104       134     253.3
9        100  '2020/12/10'     98       124     269.0
11       100  '2020/12/12'    100       120     250.7
13       100  '2020/12/13'    106       128     345.3

MATPLOTLIB FOR DATA VISUALIZATION

In [25]:
# install
%pip install matplotlib

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [26]:
import matplotlib.pyplot as plt